In [18]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [19]:
#Creating NumPy Arrays
# Step 1: Import NumPy
import numpy as np

# Step 2: Create a 1D array representing years of experience
years_exp = np.array([1, 3, 5, 7, 10, 13])
print("Years of Experience:", years_exp)

# Step 3: Create a 2D array representing sample salaries (in thousands)
salaries = np.array([[20, 30, 40], [ 50, 60, 70], [80, 90, 100,]])
print("Salary Matrix:\n", salaries)

# Step 4: Create an array of zeros and ones for placeholder analysis
zeros_array = np.zeros((2, 2)) # 2x2 zeros
ones_array = np.ones((2, 3)) # 2x3 ones
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

Years of Experience: [ 1  3  5  7 10 13]
Salary Matrix:
 [[ 20  30  40]
 [ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# PROCEDURE 2: Array Operations
# Updated: Try It Results
# Step 1: Element-wise subtraction
exp_minus_3 = years_exp - 3 # Subtract 3 years to all experience values
print("Years - 3:", exp_minus_3)

# Step 2: Element-wise division
exp_div_2 = years_exp / 2 # divide all values by 2
print("Years / 2:", exp_div_2)

# Step 3: Dot product (simulate salary projections)
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("\nDot Product:", dot_result)

# Apply exponential function
np.set_printoptions(precision=4, suppress=True)
exp_values = np.exp(years_exp)
print("\nExponential of years:\n", exp_values)

# Apply logarithmic function
np.set_printoptions(precision=4, suppress=True)
log_salaries = np.log(salaries)
print("\nLogarithm of salaries:\n", log_salaries)

Years - 3: [-2  0  2  4  7 10]
Years / 2: [0.5 1.5 2.5 3.5 5.  6.5]

Dot Product: 32

Exponential of years:
 [     2.7183     20.0855    148.4132   1096.6332  22026.4658 442413.392 ]

Logarithm of salaries:
 [[2.9957 3.4012 3.6889]
 [3.912  4.0943 4.2485]
 [4.382  4.4998 4.6052]]


In [21]:
# PROCEDURE 3: Indexing and Slicing
# Step 1: Access individual element
print("First year of experience:", years_exp[0])

# Step 2: Slice arrays
print("First two salaries:", salaries[0, :2]) # First two elements of first row

# Step 3: Access all rows for a specific column
print("Second column salaries:", salaries[:, 1])

# Step 4: Negative indexing
print("Last year of experience:", years_exp[-1])

# Updated: Try It Results
print("Try It Results:")

# Reverse the 1D years_exp array
reversed_years = years_exp[::-1]
print("\nReversed Years:", reversed_years)

# Get a subgroup: First 2 rows and first 2 columns
salary_subgroup = salaries[0:2, 0:2]
print("\nSalary Subgroup (Top-left 2x2):\n", salary_subgroup)

# Get another subgroup: Last 2 rows and last 2 columns
# (Using negative indexing for fun)
bottom_right = salaries[-2:, -2:]
print("\nSalary Subgroup (Bottom-right):\n", bottom_right)

First year of experience: 1
First two salaries: [20 30]
Second column salaries: [30 60 90]
Last year of experience: 13
Try It Results:

Reversed Years: [13 10  7  5  3  1]

Salary Subgroup (Top-left 2x2):
 [[20 30]
 [50 60]]

Salary Subgroup (Bottom-right):
 [[ 60  70]
 [ 90 100]]


In [22]:
# PROCEDURE 4: Reshaping and Dimensions
# Step 1: Reshape 1D array into 2x3 matrix for batch analysis
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)

# Step 2: Flatten 2D arrays back into 1D
flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

# Step 3: Transpose example
print("Transposed Array:\n", reshaped_exp.T)

# Updated: Try It Results
data = np.arange(1, 7)

# Reshape to 3 rows and 2 columns
reshaped_3x2 = data.reshape(3, 2)
print("Try It Results:")
print("\nReshaped into 3x2:\n", reshaped_3x2)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]
Try It Results:

Reshaped into 3x2:
 [[1 2]
 [3 4]
 [5 6]]


In [23]:
# PROCEDURE 5: Broadcasing in NumPy
# Step 1: Add a bonus array to salaries using broadcasting
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus # Adds corresponding bonus to each column
print("Salaries after bonus:\n", salaries_with_bonus)

# Updated: Try It Results
scaling_factor = 1.50

# Multiply the entire salaries matrix by the factor
scaled_salaries = salaries * scaling_factor

print("Try It Results:")
print(f"\nSalaries after {scaling_factor} scaling factor:\n", scaled_salaries)

Salaries after bonus:
 [[ 25  40  55]
 [ 55  70  85]
 [ 85 100 115]]
Try It Results:

Salaries after 1.5 scaling factor:
 [[ 30.  45.  60.]
 [ 75.  90. 105.]
 [120. 135. 150.]]


In [24]:
# PROCEDURE 6: Statistical Operations
# Step 1: Mean of years of experience
print("Mean experience:", np.mean(years_exp))

# Step 2: Standard deviation of experience
print("Std deviation of experience:", np.std(years_exp))

# Step 3: Max and Min salaries
print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries))

# Step 4: Sum of salaries
print("Sum of all salaries:", np.sum(salaries))

# Updated: Try It Results
# Compute median for years of experience
median_exp = np.median(years_exp)
print("\nTry It Results:")
print("\nMedian experience:", median_exp)

# Compute the 25th and 75th percentiles for salaries
p25 = np.percentile(salaries, 25)
p75 = np.percentile(salaries, 75)

print(f"25th percentile of salaries: {p25}")
print(f"75th percentile of salaries: {p75}")

Mean experience: 6.5
Std deviation of experience: 4.0722639076235385
Max salary: 100 Min salary: 20
Sum of all salaries: 540

Try It Results:

Median experience: 6.0
25th percentile of salaries: 40.0
75th percentile of salaries: 80.0


In [25]:
# PROCEDURE 7: NumPy Functions on Arrays
# Step 1: Apply trigonometric functions
angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

# Step 2: Apply function along rows (sum salaries per person)
salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)

# Updated: Try It Results
# Apply square root to years of experience
sqrt_exp = np.sqrt(years_exp)
print("\nTry It Results:")
print("\nSquare root of experience:", sqrt_exp)

# Define a custom function
def calculate_tax(salary_row):
    return salary_row * 0.10

# Apply it along axis 1 (rows)
tax_per_person = np.apply_along_axis(calculate_tax, 1, salaries)

print("\n10% Tax deduction per person (by row):\n", tax_per_person)

Sine of angles: [0.     0.7071 1.    ]
Cosine of angles: [1.     0.7071 0.    ]
Sum of Salaries per person: [ 90 180 270]

Try It Results:

Square root of experience: [1.     1.7321 2.2361 2.6458 3.1623 3.6056]

10% Tax deduction per person (by row):
 [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]
